apiVersion: omniverse.nvidia.com/v1
kind: Application
metadata:
  name: ${KIT_APP_NAME}
  labels:
    USD: "true"
    visualisation: "true"
spec:
  name: Omniverse USD Viewer
  description: This is a USD Viewer created for MSFT Ignite project.